### ISSUE TITLE
403 errors

### ISSUE THREAD

**Issue by cbarga** [infamousjoeg/cybr-cli#46]
When trying to retrieve safe members, I get 403 errors.

cybr cli test# cybr logon -u clb10 -a ldap -b https://pim-qa.redacted.com
Enter password: Successfully logged onto PAS as user clb10.
cybr cli test# cybr safes list-members -s DAP_PCF_RITM0315107 | grep UserName
2021/01/14 08:08:44 Failed to retrieve a list of all safe members for DAP_PCF_RITM0315107. Failed to list members of safe 'DAP_PCF_RITM0315107'. Received non-200 status code '403'
cybr cli test# cybr safes list-members -s DAP_PCF_RITM0315107 | grep UserName
            "UserName": "ChrisB"
            "UserName": "Master"
            "UserName": "Batch"
            "UserName": "Backup Users"
            "UserName": "Auditors"
            "UserName": "Operators"
            "UserName": "DR Users"
            "UserName": "Notification Engines"
            "UserName": "PVWAGWAccounts"
            "UserName": "Vault Admins"
            "UserName": "LOBUser_PCF"
            "UserName": "GG_PIM_DAP_PCF_PacMan"
cybr cli test# cybr safes list-members -s DAP_PCF_RITM0315107 | grep UserName
2021/01/14 08:08:49 Failed to retrieve a list of all safe members for DAP_PCF_RITM0315107. Failed to list members of safe 'DAP_PCF_RITM0315107'. Received non-200 status code '403'
cybr cli test# cybr safes list-members -s DAP_PCF_RITM0315107 | grep UserName
2021/01/14 08:08:52 Failed to retrieve a list of all safe members for DAP_PCF_RITM0315107. Failed to list members of safe 'DAP_PCF_RITM0315107'. Received non-200 status code '403'
cybr cli test# cybr safes list-members -s DAP_PCF_RITM0315107 | grep UserName
2021/01/14 08:08:54 Failed to retrieve a list of all safe members for DAP_PCF_RITM0315107. Failed to list members of safe 'DAP_PCF_RITM0315107'. Received non-200 status code '403'
cybr cli test# cybr safes list-members -s DAP_PCF_RITM0315107 | grep UserName
            "UserName": "ChrisB"
            "UserName": "Master"
            "UserName": "Batch"
            "UserName": "Backup Users"
            "UserName": "Auditors"
            "UserName": "Operators"
            "UserName": "DR Users"
            "UserName": "Notification Engines"
            "UserName": "PVWAGWAccounts"
            "UserName": "Vault Admins"
            "UserName": "LOBUser_PCF"
            "UserName": "GG_PIM_DAP_PCF_PacMan"
cybr cli test#

Let me know if you need me to collect logs from anywhere.

**Comment by AndrewCopeland** [comment]
First off, thank you for creating an issue. Getting feedback will help us create a more robust and solid product.

This seems backend related since a 403 is being returned. 
I will attempt to replicate in my lab. 
For the time being, what PAS version are you using?

**Comment by cbarga** [comment]
We are running 11.1.1.4
 
    On Thursday, January 14, 2021, 12:14:55 PM EST, Andrew Copeland <notifications@github.com> wrote:  
 
 


First off, thank you for creating an issue. Getting feedback will help us create a more robust and solid product.

This seems backend related since a 403 is being returned.
I will attempt to replicate in my lab.
For the time being, what PAS version are you using?

**Comment by AndrewCopeland** [comment]
@infamousjoeg  Do you think the PAS version might be related to this error?

**Comment by infamousjoeg** [comment]
@cbarga Thank you for submitting this issue!

Upon reading our API documentation for v11.1, it would appear that only the v1 API endpoint is available for that version: [https://<IIS_Server_Ip>/PasswordVault/WebServices/PIMServices.svc/Safes](https://docs.cyberark.com/Product-Doc/OnlineHelp/PAS/11.1/en/Content/SDK/Safes%20Web%20Services%20-%20List%20Safes.htm).

Our CLI currently uses only v2 API endpoints for sending requests. The `List Safes` v2 API endpoint was available in v11.1 of PAS, however, it was hidden due to still being in a beta testing phase.  The 403's you're experiencing will disappear after your next Core PAS upgrade.

I'll be sure to update our [README.md]() for v0.0.6-alpha's upcoming release to reflect a recommended minimum Core PAS and Conjur version.

@AndrewCopeland -- we should keep this bug opened for others to be able to read the solution.  I'll close this after the [README.md]() is updated.
